connection: &connection
  adapter: postgresql

development:
  <<: *connection
  database: yoklama_yeni_development

staging:
  <<: *connection
  database: yoklama_yeni_staging

production:
  <<: *connection
  database: yoklama_yeni_production

test:
  <<: *connection
  database: yoklama_yeni_test
