connection: &connection
  adapter: postgresql
  encoding: UTF-8
  username: postgres
  host: <%= ENV['POSTGRESQL_HOST'] || 'localhost'%>
  pool: <%= ENV['DB_POOL'] || 5 %>
  timeout: 5000
  port: 5432

development:
  <<: *connection
  database: yoklama_yeni_development

staging:
  <<: *connection
  database: yoklama_yeni_staging

production:
  <<: *connection
  database: yoklama_yeni_production

test:
  <<: *connection
  database: yoklama_yeni_test
